---
- hosts: web
  become: yes
  become_method: sudo
  tasks:
   - name: Make sure we have a 'tomcat' group
     group:
       name: tomcat
       state: present

   - name: Allow 'tomcat' group to have passwordless sudo
     lineinfile:
       dest: /etc/sudoers
       state: present
       regexp: '^%tomcat'
       line: '%tomcat ALL=(ALL) NOPASSWD: ALL'
       validate: 'visudo -cf %s'

   - name: Add sudoers users to tomcat group
     user: name=tomcat groups=tomcat append=yes state=present createhome=yes